# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

workNat <- function(para_tilde, LEVIER = FALSE, Model_type = 0L, fixed_pars = NULL, fixed_values = NULL) {
    .Call(`_MDSV_workNat`, para_tilde, LEVIER, Model_type, fixed_pars, fixed_values)
}

natWork <- function(para, LEVIER = FALSE, Model_type = 0L) {
    .Call(`_MDSV_natWork`, para, LEVIER, Model_type)
}

volatilityVector <- function(para, K, N) {
    .Call(`_MDSV_volatilityVector`, para, K, N)
}

probapi <- function(omega, K, N) {
    .Call(`_MDSV_probapi`, omega, K, N)
}

P <- function(para, K, N) {
    .Call(`_MDSV_P`, para, K, N)
}

levierVolatility1 <- function(ech, para, Nl = 70L, Model_type = 0L) {
    .Call(`_MDSV_levierVolatility1`, ech, para, Nl, Model_type)
}

levierVolatility <- function(ech, para, Nl = 70L, Model_type = 0L) {
    .Call(`_MDSV_levierVolatility`, ech, para, Nl, Model_type)
}

logLik <- function(para_tilde, ech, Model_type = 0L, LEVIER = FALSE, K = 2L, N = 2L, Nl = 70L, fixed_pars = NULL, fixed_values = NULL, dis = "gamma") {
    .Call(`_MDSV_logLik`, para_tilde, ech, Model_type, LEVIER, K, N, Nl, fixed_pars, fixed_values, dis)
}

logLik2 <- function(ech, para, Model_type = 0L, LEVIER = FALSE, K = 2L, N = 2L, r = 0, t = 2L, Nl = 70L, dis = "gamma") {
    .Call(`_MDSV_logLik2`, ech, para, Model_type, LEVIER, K, N, r, t, Nl, dis)
}

levierVolatilityMat <- function(ech, Levier, para, Nl = 70L, Model_type = 0L) {
    .Call(`_MDSV_levierVolatilityMat`, ech, Levier, para, Nl, Model_type)
}

R_hat <- function(H, ech, MC_sim, z_t, Levier, sig, para, Model_type = 0L, N = 3L, Nl = 70L) {
    .Call(`_MDSV_R_hat`, H, ech, MC_sim, z_t, Levier, sig, para, Model_type, N, Nl)
}

f_sim <- function(H, sig, pi_0, matP, varphi = 0, xi = 0, shape = 0, delta1 = 0, delta2 = 0) {
    .Call(`_MDSV_f_sim`, H, sig, pi_0, matP, varphi, xi, shape, delta1, delta2)
}

